#!/bin/sh

localEid=8

mctp addr add ${localEid} dev mctpi3c0
mctp link set mctpi3c0 up

mctp addr add ${localEid} dev mctpi2c0
mctp link set mctpi2c0 up

mctp addr add ${localEid} dev mctpusb0
mctp link set mctpusb0 up

